import { defineConfig } from 'vite';
import fs from 'node:fs/promises';
import path from 'node:path';
import { parseCSV, parseCSVFromRow, parseMatrix, matrixObjects, buildData } from './functions/api/data.js';
const files = ['Unified Attempt1.csv','EasyRent Prod - Apartments (1).csv','Hashkaot Renters zehavit (1).csv','Beer Sheva Monthly Report- Purchases.csv','New Occupancy  - Occupancy.csv','building-coordinates (4) (1).csv'];
const unitNumber = value => (String(value ?? '').match(/\d+/)?.[0] || '').replace(/^0+(?=\d)/, '');
export default defineConfig({ plugins: [{ name: 'local-property-data', configureServer(server) {
  server.middlewares.use('/api/local-data', async (_req, res) => { try { const t=[]; for (const n of files) t.push(await fs.readFile(path.resolve('local-data','SPREADSHEETS',n),'utf8')); const p=t.map(parseCSV); p[2]=parseCSVFromRow(t[2],1); const matrix=parseMatrix(t[4]); const d=buildData({unified:p[0],easy:p[1],renters:p[2],purchases:p[3],occupancy:matrix,coordinates:p[5]}); d.raw.coordinates=p[5]; d.raw.occupancy=matrixObjects(matrix); res.setHeader('content-type','application/json'); res.end(JSON.stringify(d)); } catch(e) { res.statusCode=500; res.end(JSON.stringify({error:e.message})); } });
  server.middlewares.use('/api/photos', async (req, res) => { try { const params=new URL(req.originalUrl || req.url, 'http://localhost').searchParams, wanted=unitNumber(params.get('yechida')), root=path.resolve('local-data','aptpics'), folders=await fs.readdir(root,{withFileTypes:true}), matching=folders.filter(x=>x.isDirectory() && unitNumber(x.name)===wanted); if(params.get('meta')==='1'){res.setHeader('content-type','application/json');res.end(JSON.stringify({hasPhotos:matching.length>0}));return;} const photos=[]; for(const folder of matching){ for(const file of await fs.readdir(path.join(root,folder.name))){ if(!/\.(jpe?g|png|webp|gif)$/i.test(file)) continue; const full=path.join(root,folder.name,file),data=await fs.readFile(full),ext=path.extname(file).slice(1).replace('jpg','jpeg'); photos.push({name:file,src:`data:image/${ext};base64,${data.toString('base64')}`}); }} res.setHeader('content-type','application/json');res.end(JSON.stringify({photos})); } catch(e) { res.statusCode=500;res.end(JSON.stringify({error:e.message})); } });
} }] });
