import { defineConfig } from 'vite';
import fs from 'node:fs/promises';
import path from 'node:path';
import { parseCSV, parseCSVFromRow, parseMatrix, matrixObjects, buildData } from './functions/api/data.js';
const files=['Unified Attempt1.csv','EasyRent Prod - Apartments (1).csv','Hashkaot Renters zehavit (1).csv','Beer Sheva Monthly Report- Purchases.csv','New Occupancy  - Occupancy.csv','building-coordinates (4) (1).csv'];
const unitNumber=v=>(String(v??'').match(/\d+/)?.[0]||'').replace(/^0+(?=\d)/,'');
export default defineConfig({plugins:[{name:'local-property-data',configureServer(server){
server.middlewares.use('/api/parcel-photos',async(req,res)=>{try{const q=new URL(req.originalUrl||req.url,'http://localhost').searchParams,w=String(q.get('parcel')||'').trim().replace(/^0+/,'').replace(/\.png$/i,''),root=path.resolve('local-data','parcelpics'),files=await fs.readdir(root),matches=files.filter(f=>f.toLowerCase()===w+'.webp');if(q.get('image')==='1'&&matches.length){res.setHeader('content-type','image/webp');res.setHeader('cache-control','public,max-age=31536000,immutable');res.end(await fs.readFile(path.resolve(root,matches[0])));return;}res.setHeader('content-type','application/json');res.end(JSON.stringify({hasPhotos:matches.length>0,photos:matches.map(f=>({name:f,src:'/api/parcel-photos?image=1&parcel='+encodeURIComponent(w)}))}));}catch(e){res.statusCode=500;res.end(JSON.stringify({photos:[],hasPhotos:false,error:e.message}));}});
server.middlewares.use('/api/local-data',async(_req,res)=>{try{const t=[];for(const n of files)t.push(await fs.readFile(path.resolve('local-data','SPREADSHEETS',n),'utf8'));const p=t.map(parseCSV);p[2]=parseCSVFromRow(t[2],1);const matrix=parseMatrix(t[4]);const d=buildData({unified:p[0],easy:p[1],renters:p[2],purchases:p[3],occupancy:matrix,coordinates:p[5]});d.raw.coordinates=p[5];d.raw.occupancy=matrixObjects(matrix);res.setHeader('content-type','application/json');res.end(JSON.stringify(d));}catch(e){res.statusCode=500;res.end(JSON.stringify({error:e.message}));}});
server.middlewares.use('/api/photos',async(req,res)=>{try{const q=new URL(req.originalUrl||req.url,'http://localhost').searchParams,wanted=unitNumber(q.get('yechida')),root=path.resolve('local-data','aptpics'),folders=await fs.readdir(root,{withFileTypes:true}),matching=folders.filter(x=>x.isDirectory()&&unitNumber(x.name)===wanted);if(q.get('meta')==='1'){res.setHeader('content-type','application/json');res.end(JSON.stringify({hasPhotos:matching.length>0}));return;}if(q.get('image')==='1'){const key=(q.get('key')||'').replace(/^apartment-pics\//,'').split('/');if(key.length!==2||unitNumber(key[0])!==wanted||!/\.(jpe?g|png|webp|gif)$/i.test(key[1])){res.statusCode=404;res.end('Not found');return;}const fp=path.resolve(root,key[0],key[1]);res.setHeader('content-type',`image/${path.extname(fp).slice(1).replace('jpg','jpeg')}`);res.setHeader('cache-control','public,max-age=31536000,immutable');res.end(await fs.readFile(fp));return;}const photos=[];for(const folder of matching)for(const file of await fs.readdir(path.join(root,folder.name)))if(/\.(jpe?g|png|webp|gif)$/i.test(file)){const key=`apartment-pics/${folder.name}/${file}`;photos.push({name:file,src:`/api/photos?image=1&yechida=${encodeURIComponent(q.get('yechida')||'')}&key=${encodeURIComponent(key)}`});}res.setHeader('content-type','application/json');res.end(JSON.stringify({photos}));}catch(e){res.statusCode=500;res.end(JSON.stringify({error:e.message}));}});
}}]});
