const CSV_NAMES = [
  'Unified Attempt1.csv',
  'EasyRent Prod - Apartments (1).csv',
  'Hashkaot Renters zehavit.csv',
  'Beer Sheva Monthly Report- Purchases.csv',
  'New Occupancy - Occupancy.csv',
  'building-coordinates (4) (1).csv',
];
let cached;

const clean = (v) => String(v ?? '').trim();
const key = (v) => clean(v).replace(/[\u200e\u200f]/g, '').replace(/\s+/g, ' ').replace(/\s*\/\s*/g, '/').replace(/[.,]+/g, '.').toLowerCase();
const date = (v) => { const m = clean(v).match(/^([A-Za-z]{3})\s+(\d{2})$/); if (!m) return null; const months = {jan:'01',feb:'02',mar:'03',apr:'04',may:'05',jun:'06',jul:'07',aug:'08',sep:'09',oct:'10',nov:'11',dec:'12'}; return months[m[1].toLowerCase()] ? `${months[m[1].toLowerCase()]}/15/${Number(m[2]) + 2000}` : null; };
const ownerGroup = (owner) => /השקעות דרום|וייס זאב דוד/.test(owner||'') ? 'Weiss' : /קרן אבירם|מוריס דוד דניאל|קרן אבירם בעמ|רוקון נאמנים/.test(owner||'') ? 'Morris' : 'Other';
export function parseMatrix(text) { const rows=[]; let row=[],cell='',quoted=false; for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1]; if(c==='"'&&quoted&&n==='"'){cell+='"';i++;continue} if(c==='"'){quoted=!quoted;continue} if(!quoted&&c===','){row.push(cell);cell='';continue} if(!quoted&&(c==='\n'||c==='\r')){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>clean(x)))rows.push(row.map(clean));row=[];cell='';continue} cell+=c;} if(cell||row.length){row.push(cell);rows.push(row.map(clean));} return rows; }
export function parseCSV(text) { const rows=parseMatrix(text); const headers=rows.shift()||[]; return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??'']))); }
export function parseCSVFromRow(text,index=0) { const rows=parseMatrix(text),headers=rows[index]||[]; return rows.slice(index+1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??'']))); }
export function matrixObjects(rows){const width=Math.max(...rows.map(r=>r.length),0);return rows.map(r=>Object.fromEntries(Array.from({length:width},(_,j)=>[`Column ${String.fromCharCode(65+j)}`,r[j]??''])));}
function matrix(text) { return parseCSV(text); }
async function readCSV(bucket, prefix, name) { if(!bucket?.list||!bucket?.get) throw new Error('R2 binding PROPERTY_DATA is not configured on this Pages deployment'); const normalizeName=(v)=>v.toLowerCase().replace(/[\u200e\u200f]/g,'').replace(/\s+/g,' ').trim(); const base=normalizeName(name).replace(/ \(1\)(?=\.csv$)/,''); const candidates=[name,name.replace('.csv',' (1).csv'),name.replace(' - ','  - ')].map(normalizeName); const listed=await bucket.list({prefix}); const object=listed.objects.find(o=>{const key=normalizeName(o.key);return candidates.some(wanted=>key.endsWith(wanted))||key.endsWith(base)}); if(!object) throw new Error(`Missing R2 file: ${prefix}${name}. Files must be inside the SPREADSHEETS/ prefix.`); const file=await bucket.get(object.key); if(!file) throw new Error(`Unable to read R2 object: ${object.key}`); return file.text(); }
export function buildData(raw) {
  const unified=raw.unified, easy=raw.easy, renters=raw.renters, purchases=raw.purchases, occupancy=raw.occupancy;
  const apartments=[]; const byId=new Map(), byUnifiedEasyId=new Map(), byUnit=new Map(), byEasy=new Map();
  unified.forEach(row=>{ const id=clean(Object.values(row)[0]); if(!id||byId.has(id))return; const a={id, unified:{}, easyRent:{}, renter:{}, bills:{water:[],arnona:[],gas:[]},transactions:[],rents:[],photos:[]}; for(const [k,v] of Object.entries(row))a.unified[k]=clean(v); a.unit=clean(row['EASYPROD - Appt ID']||row['NEW OCCUPANCY UNIT']||Object.values(row)[1]); a.occupancyUnit=clean(row['NEW OCCUPANCY UNIT']); a.yechida=clean(row['ZEHAVIT yechida']);a.address=clean(row['NEW OCCUPANCY ADRESSS']||row['zehavit address']);const fallback=a.address.match(/^(.*?)[\s]+(\d+)\s*\/\s*([^/]+)$/);if(fallback){a.buildingNumber=fallback[2];a.apartmentNumber=fallback[3].trim()} apartments.push(a); byId.set(id,a);if(a.unified['EASYPROD - UniquID'])byUnifiedEasyId.set(clean(a.unified['EASYPROD - UniquID']),a);if(a.unit)byUnit.set(key(a.unit),a);if(a.occupancyUnit)byUnit.set(key(a.occupancyUnit),a);if(a.yechida)byUnit.set(key(a.yechida),a); });
  easy.forEach(row=>{ const id=clean(row.UniquID||row['UniquID ']); const a=byUnifiedEasyId.get(id); if(!a)return; a.easyRent=Object.fromEntries(Object.entries(row).map(([k,v])=>[k,clean(v)])); a.buildingNumber=clean(row['Street Number']);a.apartmentNumber=clean(row.Appt);a.entrance=clean(row.Entrance);a.address=[row.Street,row['Street Number']].filter(Boolean).map(clean).join(' ');a.fullAddress=[a.address,row.Appt&&`Apt ${row.Appt}`,row.Entrance&&`Entrance ${row.Entrance}`].filter(Boolean).join(', '); a.altAddress=clean(row.AltAddress); byEasy.set(id,a); });
  renters.forEach(row=>{const a=byUnit.get(key(row['יחידה']||row['ZEHAVIT yechida']));if(!a)return;a.renter=Object.fromEntries(Object.entries(row).map(([k,v])=>[k,clean(v)])); for(const [from,to,type] of [['BR','CC','water'],['CD','CO','arnona'],['CP','DA','gas']]){const headers=Object.keys(row),s=headers.indexOf(from),e=headers.indexOf(to);if(s<0||e<0)continue;headers.slice(s,e+1).forEach(h=>{const n=Number(String(row[h]).replace(/[^0-9.-]/g,''));if(n)a.bills[type].push({month:h,value:n});});}});
  purchases.forEach(row=>{const purchaseId=clean(row.UNIT||row['Unit']||row['UNIT ']);const a=byUnifiedEasyId.get(purchaseId)||byEasy.get(purchaseId);if(a)a.transactions.push({...row,canonicalId:a.id,type:'Purchase'});});
  const occMatrix=Array.isArray(occupancy?.[0])?occupancy:null;
  if(occMatrix){const unitRow=occMatrix[7]||[],monthCol=0;for(let col=1;col<unitRow.length;col++){const a=byUnit.get(key(unitRow[col]));if(!a)continue;for(let row=110;row<occMatrix.length;row++){const d=date(occMatrix[row]?.[monthCol]);if(!d)continue;const raw=clean(occMatrix[row]?.[col]);if(!raw)continue;const numeric=/^[-+]?\d[\d,]*(?:\.\d+)?$/.test(raw),value=numeric?Number(raw.replace(/,/g,'')):0;a.rents.push({date:d,value,display:raw,status:numeric?'':raw.toUpperCase(),label:new Date(d)<new Date()?'Rent received':'Rent expected'});}}}
  else {const occRows=occupancy;const headers=Object.keys(occRows[0]||{}),unitRow=occRows[0]||{};headers.slice(1).forEach(h=>{const a=byUnit.get(key(unitRow[h]));if(!a)return;occRows.slice(2).forEach(r=>{const d=date(r[headers[0]]),raw=clean(r[h]);if(!d||!raw)return;const numeric=/^[-+]?\d[\d,]*(?:\.\d+)?$/.test(raw),value=numeric?Number(raw.replace(/,/g,'')):0;a.rents.push({date:d,value,display:raw,status:numeric?'':raw.toUpperCase(),label:new Date(d)<new Date()?'Rent received':'Rent expected'});});});}
  for(const a of apartments){const seen=new Set();a.rents=a.rents.filter(r=>{const k=`${a.id}|${r.date}`;if(seen.has(k))return false;seen.add(k);return true}).sort((x,y)=>y.date.localeCompare(x.date));}
  const coords=raw.coordinates||[],buildingRows=apartments.map(a=>{const owner=clean(a.renter['בעל הדירה']||a.renter.Owner||a.easyRent['Owner 1']);const cls=clean(a.easyRent.Class),streetNumber=clean(a.buildingNumber),entrance=clean(a.entrance),coord=coords.find(c=>clean(c.streetNumber)===streetNumber&&(!entrance||clean(c.entrance)===entrance));return {Building:a.address||a.unified['NEW OCCUPANCY ADRESSS']||'Address pending',Apartment:a.apartmentNumber||a.unit||a.unified['EASYPROD - Appt ID']||a.id,Entrance:entrance,Floor:clean(a.easyRent.Floor||a.renter['קומה']),Parcel:clean(a.easyRent.Parcel),Size:clean(a.easyRent.Size),Garden:clean(a.easyRent.Garden),Rooms:clean(a.renter['חדרים']),InitialCost:clean(a.easyRent.Invested),Tenant:clean(a.renter['שמות']||a.renter.Tenant||a.renter.Name||a.renter['שם השוכר']),TenantId:clean(a.renter['ת.ז']||a.renter['תעודת זהות']),TenantPhones:clean(a.renter['טלפונים']||a.renter['טלפון']||a.renter['טלפון נייד']),TenantEmail:clean(a.renter['כתובת אימייל']||a.renter['אימייל']||a.renter.Email),GroupOwner:ownerGroup(owner),LeaseStart:clean(a.renter['תחילת חוזה']||a.renter['תאריך התחלה']),LeaseEnd:clean(a.renter['סיום חוזה']||a.renter['תאריך סיום']),LeaseStatus:clean(a.renter['סטטוס חוזה']||a.renter.Status),Transactions:a.transactions,Rents:a.rents,lat:coord?.lat||'',lng:coord?.lng||'','Truly Unique ID':a.id,Yechida:a.yechida||'',Owner:owner,Class:cls,'Yechida status':a.yechida?'Has Yechida':'No Yechida'};}).sort((a,b)=>a.Building.localeCompare(b.Building)||(parseInt(a.Apartment)||9999)-(parseInt(b.Apartment)||9999));
  return {apartments,raw:{unified,easyRent:easy,renters,purchases,occupancy,buildings:buildingRows},meta:{apartmentCount:apartments.length,loadedAt:new Date().toISOString(),sources:{unified:{rows:unified.length,matched:apartments.length},easyRent:{rows:easy.length,matched:[...byEasy.values()].length},renters:{rows:renters.length,matched:apartments.filter(a=>Object.keys(a.renter).length).length},purchases:{rows:purchases.length,matched:apartments.reduce((n,a)=>n+a.transactions.length,0)},occupancy:{rows:occupancy.length,matched:apartments.reduce((n,a)=>n+a.rents.length,0)}},missingYechida:apartments.filter(a=>!a.yechida).length,withYechida:apartments.filter(a=>a.yechida).length}};
}
export async function onRequestGet({env,request}) { try { if(!cached) { const prefix='SPREADSHEETS/'; const texts=await Promise.all(CSV_NAMES.map(n=>readCSV(env.PROPERTY_DATA,prefix,n))); const parsed=texts.map(parseCSV); parsed[2]=parseCSVFromRow(texts[2],1); const occupancyMatrix=parseMatrix(texts[4]); cached=buildData({unified:parsed[0],easy:parsed[1],renters:parsed[2],purchases:parsed[3],occupancy:occupancyMatrix,coordinates:parsed[5]}); cached.raw.coordinates=parsed[5]; cached.raw.occupancy=matrixObjects(occupancyMatrix); } return Response.json(cached,{headers:{'cache-control':'private, max-age=300'}}); } catch(e) { return Response.json({error:e.message},{status:500}); } }
