import React,{useMemo,useState}from'react';

const columns=[['Building','Building address'],['Apartment','Apartment #'],['Parcel','Parcel'],['Entrance','Entrance'],['Yechida','Yechida'],['Owner','Owner'],['GroupOwner','Owner group'],['Tenant','Tenant'],['Truly Unique ID','Canonical ID']];
const value=(row,key)=>String(row[key]??'');
export default function SpreadBuildings({rows=[],onOpenApartment}){
  const [query,setQuery]=useState(''); const [sort,setSort]=useState({key:'Building',dir:1});
  const duplicates=useMemo(()=>{const map=new Map();rows.forEach(row=>{const key=`${row.Building||'Address pending'}|${String(row.Apartment||'').replace(/^0+(?=\d)/,'')}`;if(!map.has(key))map.set(key,[]);map.get(key).push(row)});return map},[rows]);
  const problemFor=row=>{const key=`${row.Building||'Address pending'}|${String(row.Apartment||'').replace(/^0+(?=\d)/,'')}`,items=duplicates.get(key)||[];if(items.length<2)return '';const yechidas=[...new Set(items.map(x=>x.Yechida).filter(Boolean))];const owners=[...new Set(items.map(x=>x.Owner).filter(Boolean))];return `Duplicate apartment number: ${items.length} records for ${row.Building||'Address pending'} / apartment ${row.Apartment||'—'}. Yechida values: ${yechidas.join(', ')||'none'}. Owners: ${owners.join(', ')||'not recorded'}. Review whether these are co-ownership records or a duplicated source row.`};
  const toggle=key=>setSort(s=>s.key===key?{key,dir:-s.dir}:{key,dir:1});
  const filtered=useMemo(()=>rows.filter(row=>columns.some(([key])=>value(row,key).toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>value(a,sort.key).localeCompare(value(b,sort.key),undefined,{numeric:true,sensitivity:'base'})*sort.dir),[rows,query,sort]);
  return <div className="spread-buildings-page"><div className="directory-head"><div><span className="pill">SPREAD BUILDINGS</span><h2>Building apartment index</h2><p>Building, apartment, parcel, entrance, ownership, and tenant records.</p></div><strong>{filtered.length} of {rows.length} rows</strong></div><div className="spread-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter by address, apartment, parcel, entrance, Yechida, owner, group, or tenant…"/><span>{filtered.length} matching rows · duplicate records highlighted</span></div><div className="spread-table-wrap"><table className="spread-table"><thead><tr>{columns.map(([key,label])=><th key={key}><button onClick={()=>toggle(key)}>{label}{sort.key===key?(sort.dir>0?' ↑':' ↓'):''}</button></th>)}</tr></thead><tbody>{filtered.map(row=>{const problem=problemFor(row);return <tr key={row['Truly Unique ID']} className={problem?'spread-problem-row':''} title={problem||undefined}><td>{row.Building||'Address pending'}</td><td className={problem?'spread-problem-cell':''}>{row.Apartment||'—'}{problem&&<span className="spread-problem-badge">!</span>}</td><td>{row.Parcel||'—'}</td><td>{row.Entrance||'—'}</td><td>{row.Yechida?<button className="spread-unit-link" onClick={()=>onOpenApartment?.(row)}>{row.Yechida}</button>:'—'}</td><td>{row.Owner||'—'}</td><td>{row.GroupOwner||'Other'}</td><td>{row.Tenant||'—'}</td><td>{row['Truly Unique ID']||'—'}</td></tr>})}</tbody></table></div></div>;
}
